name: bench
on: 
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Run
      timeout-minutes: 350
      run: |
        wget -q 'https://github.com/maintell/webBenchmark/releases/download/0.6/webBenchmark_linux_x64' && chmod +x webBenchmark_linux_x64
        ./webBenchmark_linux_x64 -c 64 -s "http://152.70.85.21:32400/web/js/main-179-289bdfc5072e1e847598-plex-4.76.1.22469-3117cd9.js"
