name: docker-compose
on: 
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 1024
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - uses: actions/checkout@v2
      - name: Build the stack
        env:
          SA_URL: ${{ secrets.SA_URL }}
          SA_SECRET: ${{ secrets.SA_SECRET }}
          ARIA2C_SECRET: ${{ secrets.ARIA2C_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: docker-compose up -d
      - name: Check running containers
        run: | 
          docker ps -a
          df -h
          curl ipinfo.io
      - name: Add Tunnle
        env:
          TUNNEL_ORIGIN_CERT: '/home/runner/work/aations/aations/cert.pem'
        run: | 
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && sudo dpkg -i cloudflared.deb
          echo "${{ secrets.TUNNEL_YML }}" > easydown.yml
          echo "${{ secrets.TUNNEL_JSON }}" > easydown.json
          echo "${{ secrets.CERT_PEM }}" > cert.pem && pwd && ls -a
          cloudflared tunnel --config easydown.yml run&
      - name: Run test suite
        run: sleep 6h
