name: docker
on: 
#  schedule:
#    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
      - name: Check running containers
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          docker ps -a 
          df -h
          curl ipinfo.io
          sleep 20s
          gh workflow run test.yml
