name: Transfers
on:
  workflow_dispatch:
jobs:
  AutoSyncProcess:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Rclone Install
      run: |
        wget -q https://github.com/Kwok1am/rclone-ac/releases/download/gclone/gclone.gz
        gunzip gclone.gz
        sudo mv gclone /usr/bin/gclone
        chmod +x /usr/bin/gclone
        sudo apt install unrar -y -q
        pwd
        ls -a
  AutoSyncProcess2:
    runs-on: ubuntu-latest
    needs: AutoSyncProcess
    - uses: actions/checkout@v2.1.0
    - name: Rclone Install
      run: |
        gclone -help
        pwd
        ls -a
