name: test
on: 
#  schedule:
#    - cron: '0 */6 * * *'
  workflow_dispatch:
  repository_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-dotnet: 'true'
          remove-android: 'true'

      - uses: actions/checkout@v2
      - name: Check running containers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          docker ps -a 
          df -h
          curl ipinfo.io
          sleep 10s
          curl -X POST https://api.github.com/repos/KwokLam/aations/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          --data '{"event_type": "TRIGGER_KEYWORDS"}'
